version: 1.0.0.{build}
os: Unstable
install:
  - ps: |
      Write-verbose -Message "PSVersion: $($PSVersionTable.PSVersion.Major)" -Verbose
      &nuget.exe install PoshBuildTools -source https://ci.appveyor.com/nuget/PoshBuildTools -outputDirectory "$env:USERPROFILE\Documents\WindowsPowerShell\Modules\" -ExcludeVersion -Version 1.0.0.130
      Import-Module PoshBuildTools
      $moduleInfoList = New-BuildModuleInfo -Auto
      Write-verboseBuildModuleInfo -moduleInfoList $moduleInfoList
      Invoke-AppveyorInstall -skipConvertToHtmlInstall

build_script:
  - ps: |
      Invoke-AppveyorBuild -moduleInfoList $moduleInfoList      

on_finish:
  - ps: |
      Write-Info 'Creating Example zip ...'
      7z a -tzip .\out\examples.zip .\examples\*.html
      Invoke-AppveyorFinish -moduleInfoList $moduleInfoList -expectedModuleCount 1

cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache
test_script:
  - ps: |
      Import-Module .\ConvertToHtml -force
      Invoke-AppveyorTest -moduleInfoList $moduleInfoList 
